### ISSUE TITLE
Add desc

### ISSUE THREAD

**Issue by htazad** [HasThemes/wp-plugin-manager#13]
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/873d1835-93dd-4c4e-b588-66cd0b9b7037">

**Comment by htazad** [comment]
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/fb953151-ea40-4cc4-89f4-85140e7f508e">

**Comment by yeasin-hastechit** [comment]
Description has been added.
